In [17]:
import numpy as np
import torch
import torch.nn.functional as F

In [18]:
n_classes = 3
n_examples = 20

y = torch.LongTensor(np.random.rand(n_examples)*n_classes)
y_pred = torch.FloatTensor(np.random.rand(n_examples, n_classes))
y_pred_softmax = torch.nn.Softmax(dim=1)(y_pred)
print(y_pred_softmax.sum(dim=1))

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000])


In [19]:
print(y.shape, y_pred.shape)

loss = F.cross_entropy(y_pred, y)
print(loss.item())

torch.Size([20]) torch.Size([20, 3])
1.1360231637954712


In [13]:
weights = torch.FloatTensor([1, 2, 4])
loss = F.cross_entropy(y_pred, y, weights)
print(loss.item())

1.2019320726394653


In [6]:
y_pred

tensor([[0.9976, 0.6257, 0.0244],
        [0.1534, 0.5615, 0.0723],
        [0.0077, 0.5946, 0.6171],
        [0.8134, 0.0241, 0.3092],
        [0.1727, 0.2388, 0.9217]])

In [7]:
y

tensor([1, 0, 0, 0, 1])